defaults:
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: tpe

# global
exp_root_folder: ./experiments/generators_hpo
random_state: 42
device: cuda:0

# hyperparameter grid definition
hydra:
  sweeper:
    direction:
    - maximize
    - maximize
    study_name: ${generator.label}-${hpo_objective}-${now:%Y/%m/%d}-${now:%H:%M:%S}
    storage: sqlite:///${exp_root_folder}/generators_hpo.sqlite3
    n_jobs: 1
    n_trials: 25
    params:
      generator.lr: tag(log, interval(0.00001, 0.003))
      generator.batch_size: choice(2048, 4096)
      generator.num_timesteps: choice(100, 1000)
      generator.n_iter: choice(500, 1000) # number of epochs for training
      generator.n_layers_hidden: range(2, 8)
      generator.n_units_hidden: choice(128, 256, 512, 1024)
      generator.dropout: interval(0.0, 0.5)
  sweep:
    dir: ${exp_root_folder}/${generator.label}/utility_large_privacy_05

hpo_objective: ["utility_large", "authenticity"]
privacy_weight: 0.5

data:
  label: "adult"
  # label: "census"
  folder: data # relative path
  path: ./${data.folder}/${data.label}
  tapas_data_processor: 
    _target_: tools.tapas.tapas_data_processors.AdultDataProcessor
    # _target_: tools.tapas.tapas_data_processors.CensusDataProcessor
  train_size: 0.8
  random_state: ${random_state}
  num_original_records_large: 'all' # 'all'
  target_column: 'income'

generator:
  _target_: tools.tapas.generators.SynthcityGenerator
  label: TabDDPM
  plugin_name: ddpm
  categorical_limit: 42 # extremely important! Othwerise, the Industry columns will be considered as continuous
  lr: 0.002
  batch_size: 1024
  num_timesteps: 1000
  n_iter: 1000 # number of epochs for training
  n_layers_hidden: 3
  n_units_hidden: 256
  dropout: 0.0
  random_state: ${random_state}

evaluator:
  random_state: ${random_state}
  num_synthetic_records_large: 'all' # 'all'
  num_original_records_small: 1000
  num_synthetic_records_small: 1000 # 'all'
  n_repetitions_validation: 1 # number of iteration for bootstrap (for each seed)
  n_repetitions_test: 100
  n_repetitions_small: 5
  n_val_samples_small: 200
  n_cv_folds: 3
  data:
    target_column: ${data.target_column}
    train_size: 0.8
  classification_optimizer:
    random_state: ${random_state}
    data:
      target_column: ${data.target_column}
    pipeline:
      numerical_scaler: 
        _target_: sklearn.preprocessing.StandardScaler
      classifier:
        _target_: xgboost.XGBClassifier
        random_state: ${random_state}
        eta: 0.7273798583599224
        gamma: 1.190597224833105
        max_depth: 3
        lambda: 1.5199930818015779
        alpha: 1.1966139886551352
        min_child_weight: 7.790424738260907
        subsample: 0.9448578289733992
        n_estimators: 61
    eval:
      f1_avg: 'macro'