import warnings

import pandas as pd
import numpy as np

import seaborn as sns
import matplotlib.pyplot as plt
from scipy.stats.contingency import association

try:
    from ydata_profiling import ProfileReport
except ImportError:
    warnings.warn("ydata_profiling is not installed. You can install it with 'pip install -U ydata-profiling'.")


def generate_census_profiling_report(census, output_folder, output_file_name='census_report.html', is_export_html=True):
    """
    Generate a ydata profiling report for the census dataset.
    For more information about setting variables, 
    see https://docs.profiling.ydata.ai/latest/advanced_settings/available_settings/#correlations.

    Parameters
    ----------
    census : pd.DataFrame
        The census dataset.
    output_folder : pathlib.Path
        The folder to save the report.
    output_file_name : str, optional
        The name of the output file, by default 'census_eda_report.html'

    Returns
    -------
    pandas_profiling.ProfileReport
        The profiling report.
    """

    profiling_data = census.copy()
    ProfileReport(profiling_data)

    report = profiling_data.profile_report(
        title="Original - 2011 UK Census Microdata",
        dataset={
            "description": "This report was generated by replacing all '-9' undefined values by None. The data come from the original 2011 UK Census Microdata dataset.",
            "url": "https://www.ons.gov.uk/census/2011census/2011censusdata/censusmicrodata",
        },
        type_schema={col:"categorical" for col in census.columns},
        explorative=True,
        vars={
            "cat": {
                "length": False,
                "characters": False,
                "words": False,
                },
        },
        missing_diagrams={
            "matrix": True,
            "heatmap": True
        },
        correlations={
            "auto": {
                "calculate": False
            },
            "cramers": {
                "calculate": True
            }
        },
    )

    if is_export_html:
        with warnings.catch_warnings():
            warnings.simplefilter(action='ignore', category=FutureWarning)
            report.to_file(output_folder/output_file_name)

    return report


def generate_adults_profiling_report(adults, numerical_columns, categorical_columns, output_folder, output_file_name='adults_report.html', is_export_html=True):
    profiling_data = adults.copy()
    ProfileReport(profiling_data)

    report = profiling_data.profile_report(
        title="Original - Adult income dataset",
        dataset={
            "description": "This report was generated on the Adult income dataset.",
            "url": "https://archive.ics.uci.edu/dataset/2/adult",
        },
        type_schema=\
            {col:"numerical" for col in numerical_columns}.update({col:"categorical" for col in categorical_columns}),
        explorative=True,
        vars={
            "cat": {
                "length": False,
                "characters": False,
                "words": False,
                },
        },
        missing_diagrams={
            "matrix": True,
            "heatmap": True
        },
        correlations={
            "auto": {
                "calculate": True
            }
        },
    )

    if is_export_html:
        with warnings.catch_warnings():
            warnings.simplefilter(action='ignore', category=FutureWarning)
            report.to_file(output_folder/output_file_name)

    return report

#
#   Univariate Analysis
#
def get_categorical_features_stats(df, is_replace_na=False, round_decimals=2):
    """
    Get the statistics of the categorical features of a dataframe.

    Parameters
    ----------
    df : pd.DataFrame
        The dataframe to analyze.
    replace_na : bool, optional
        The value to replace as NA, by default -9.

    Returns
    -------
    pd.DataFrame
        The statistics of the categorical features.
    """
    stats_cat = df.describe(include=['object', 'category']).T
    stats_cat['freq'] = stats_cat['freq'].astype(int)
    stats_cat['top_%'] = stats_cat['freq']/len(df)*100
    stats_cat = stats_cat.rename(columns={'freq':'top_freq'})

    if round_decimals is not None:
        stats_cat = stats_cat.round(round_decimals)

    return stats_cat.T

#
#   Multivariate Analysis
#

def compute_cramer_v_contingency_matrix(df, categorical_features):
    """
    Compute the Cramér's V matrix for a dataframe and a list of categorical features.


    Don't apply yates correction if one cell of the table has an **expected** count smaller than 5, according to 
    # https://en.wikipedia.org/wiki/Yates%27s_correction_for_continuity.
    # Yates correction prevents overestimation of statistical significance for small data.

    Parameters
    ----------
    df : pd.DataFrame
        The dataframe to analyze.
    categorical_features : list
        The list of categorical features to analyze.

    Returns
    -------
    pd.DataFrame
        The Cramér's V matrix.
    """
    cramer_v = pd.DataFrame(index=categorical_features, columns=categorical_features)

    for feature_1 in categorical_features:
        for feature_2 in categorical_features:
            obs2x2 = pd.crosstab(df[feature_1], df[feature_2])
            expected = np.outer(obs2x2.sum(axis=1), obs2x2.sum(axis=0)) / obs2x2.sum().sum()
            # Yates correction
            correction = np.any(expected < 5)
            cramer_v.loc[feature_1, feature_2] = association(obs2x2, method='cramer', correction=correction)
    return cramer_v.astype(np.float64)


def plot_cramer_v_heatmap(cramer_v_contingency_matrix, label="", ax=None):
    """
    Plot the Cramér's V matrix heatmap.
    
    Parameters:
    -----------
    cramer_v_contingency_matrix: pd.DataFrame
        The Cramér's V matrix of contingency coefficients.
    label: str
        The label to add to the title of the plot.
    ax: matplotlib.axes.Axes
        The axes to plot the heatmap on.

    Returns:
    --------
    None
    """
    sns.heatmap(cramer_v_contingency_matrix.round(2), cmap='coolwarm', annot=True, vmin=0, vmax=1, ax=ax)
    ax.set_title(f"Cramér's V contingency coefficient heatmap {label}")


def get_overall_stats(df, nan_value, round_decimals=2):
    stats = {}
    stats['n_rows'] = len(df)
    stats['n_cols'] = len(df.columns)
    stats['n_na_rows'] = len(df)-len(df.replace(nan_value, np.nan).dropna())
    stats['na_rows_%'] = stats['n_na_rows']/stats['n_rows']*100
    stats['n_duplicates'] = df.duplicated().sum()
    stats['duplicates_%'] = stats['n_duplicates']/stats['n_rows']*100
    stats = pd.DataFrame(stats, index=['dataset'])

    return stats if round_decimals is None else stats.round(round_decimals)