# the base config should only define how the outputs are generated.
exp_root_folder: ./experiments

hydra:
  # single run output dir
  run:
    dir: ${exp_root_folder}/${data.label}/${threat_model.abbreviation}/${attack.label_short}/${threat_model.generator_knowledge.generator.label}/${threat_model.target_record_indice}/${now:%Y%m%d}-${now:%H%M%S}

  # sweeper output dir (multirun)
  sweep:
    dir: ${exp_root_folder}/${data.label}/${threat_model.abbreviation}/${attack.label_short}/${threat_model.generator_knowledge.generator.label}/${threat_model.target_record_indice}
    subdir: ${now:%Y%m%d}-${now:%H%M%S}
