defaults:
  - data: adult
  - threat_model: aux_blackbox_mia
  - attack: achilles_heel
  - hydra_config
  - global
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
  - _self_

random_seed: 42
device: cuda:0

threat_model:
  target_record_indice: 4444
  data_knowledge:
    aux_data_size: 50000
    test_data_size: 25000
    real_datasets_size: 10000
  generator_knowledge:
    synth_datasets_size: 10000
    generator:
      _target_: tools.tapas.generators.SynthcityGenerator
      label: TabDDPM
      plugin_name: ddpm  
      lr: 0.00013067363723152697
      batch_size: 2048
      num_timesteps: 100
      n_iter: 1000
      n_layers_hidden: 4
      n_units_hidden: 128
      dropout: 0.000871018582934785
      categorical_limit: 42
      random_state: ${random_seed}

attack:
  num_training_samples: 1000
  num_testing_samples: 200
  attack_object:
    high_order: 15