defaults:
  - data: adult
  - threat_model: aux_blackbox_mia
  - attack: achilles_heel
  - hydra_config
  - global
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
  - _self_

random_seed: 42

threat_model:
  target_record_indice: 4444
  data_knowledge:
    aux_data_size: 10000
    test_data_size: 5000
    real_datasets_size: 1000
  generator_knowledge:
    synth_datasets_size: 1000
    generator:
      _target_: tapas.generators.ReprosynGenerator
      label: BayNet
      reprosyn_class: reprosyn.methods.DS_BAYNET
      histogram_bins: 2
      degree: 3
      random_state: ${random_seed}

attack:
  # num_training_samples: 4000
  num_training_samples: 1000
  num_testing_samples: 200
  attack_object:
    high_order: 15