defaults:
  - data: census
  - threat_model: aux_blackbox_mia
  - attack: achilles_heel
  - hydra_config
  - global
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
  - _self_

random_seed: 42

threat_model:
  target_record_indice: 4444
  data_knowledge:
    aux_data_size: 50000
    test_data_size: 25000
    real_datasets_size: 10000
  generator_knowledge:
    synth_datasets_size: 10000
    generator:
      _target_: tools.tapas.generators.SynthcityGenerator
      label: TabDDPM
      plugin_name: ddpm  
      lr: 0.00035281869402134275
      batch_size: 4096
      num_timesteps: 1000
      n_iter: 500
      n_layers_hidden: 3
      n_units_hidden: 1024
      dropout: 0.3626280413772279
      random_state: ${random_seed}
attack:
  num_training_samples: 1000
  num_testing_samples: 200
  attack_object:
    high_order: 17