defaults:
  - attack_base
  - _self_

label: QueryBasedAttackFast
label_short: ah

attack_object:
  _target_: tools.tapas.query_based_attack.QueryBasedAttackFast
  low_order: 1
  high_order: ??
  num_meta_features: 100000
  random_state: ${random_seed}
  model: 
    _target_: sklearn.ensemble.RandomForestClassifier
    n_estimators: 100
    max_depth: 10
    verbose: 0
    random_state: ${random_seed}

paths:
  meta_classifier_path: meta_classifier.pkl