# black box shadow modelling MIA base configuration, to make sure that no variables are 
# forgotten when declaring a new class
defaults:
  - threat_model_base
  - _self_

abbreviation: aux-bb-mia
target_record_indice: ???

data_knowledge: # AuxiliaryDataKnowledge
  kind: auxiliary
  aux_data_size: ???
  test_data_size: ???
  real_datasets_size: ???

generator_knowledge: # BlackBoxAttack
  kind: black-box
  synth_datasets_size: ???
  generator:
    _target_: ???
    label: ???
    random_state: ${random_seed}

attacker_goal: # TargetedMia
  kind: targeted-mia
  generate_pairs: true
  replace_target: true